/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // ─── Midnight & Gold Prestige Design System ───────────────────────────
        'primary':               '#000000',
        'on-primary':            '#ffffff',
        'primary-container':     '#131b2e',
        'on-primary-container':  '#7c839b',
        'secondary':             '#735c00',
        'on-secondary':          '#ffffff',
        'secondary-container':   '#fed65b',
        'on-secondary-container':'#745c00',
        'secondary-fixed':       '#ffe088',
        'secondary-fixed-dim':   '#e9c349',
        'on-secondary-fixed':    '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary':              '#000000',
        'on-tertiary':           '#ffffff',
        'tertiary-container':    '#1b1b1b',
        'on-tertiary-container': '#848484',
        'error':                 '#ba1a1a',
        'on-error':              '#ffffff',
        'error-container':       '#ffdad6',
        'on-error-container':    '#93000a',
        'background':            '#f7f9fb',
        'on-background':         '#191c1e',
        'surface':               '#f7f9fb',
        'on-surface':            '#191c1e',
        'on-surface-variant':    '#45464d',
        'surface-variant':       '#e0e3e5',
        'surface-bright':        '#f7f9fb',
        'surface-dim':           '#d8dadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container':     '#eceef0',
        'surface-container-high':'#e6e8ea',
        'surface-container-highest':'#e0e3e5',
        'surface-tint':          '#565e74',
        'outline':               '#76777d',
        'outline-variant':       '#c6c6cd',
        'inverse-surface':       '#2d3133',
        'inverse-on-surface':    '#eff1f3',
        'inverse-primary':       '#bec6e0',
        'primary-fixed':         '#dae2fd',
        'primary-fixed-dim':     '#bec6e0',
        'on-primary-fixed':      '#131b2e',
        'on-primary-fixed-variant':'#3f465c',
        'tertiary-fixed':        '#e2e2e2',
        'tertiary-fixed-dim':    '#c6c6c6',
        'on-tertiary-fixed':     '#1b1b1b',
        'on-tertiary-fixed-variant':'#474747',
      },
      fontFamily: {
        serif: ['Noto Serif', 'Georgia', 'serif'],
        sans:  ['Inter', 'system-ui', 'sans-serif'],
        'h1':  ['Noto Serif', 'serif'],
        'h2':  ['Noto Serif', 'serif'],
        'h3':  ['Noto Serif', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm':['Inter', 'sans-serif'],
      },
      fontSize: {
        'h1':      ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2':      ['36px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3':      ['24px', { lineHeight: '1.4', letterSpacing: '0',       fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0',       fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0',       fontWeight: '400' }],
        'label-sm':['12px', { lineHeight: '1',   letterSpacing: '0.05em',  fontWeight: '600' }],
      },
      spacing: {
        'base':          '8px',
        'stack-sm':      '12px',
        'stack-md':      '24px',
        'stack-lg':      '48px',
        'gutter':        '24px',
        'margin':        '32px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        'level-1': '0px 4px 20px rgba(15, 23, 42, 0.05)',
        'level-2': '0px 12px 40px rgba(15, 23, 42, 0.1)',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}
